/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package satranckulubu;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import static java.lang.System.in;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author casper
 */
public class GirisEkrani extends javax.swing.JFrame {
    ImageIcon ic = new ImageIcon("image\\at.jpg");
    public GirisEkrani() {
       
          //DosyaOku();
        setIconImage(ic.getImage());
        initComponents();
        setResizable(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
      
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void MinitComponents() {

        girisEkrani = new javax.swing.JPanel();
        sifre = new javax.swing.JPasswordField();
        kullaniciAdi = new java.awt.TextField();
        butonGiris = new javax.swing.JButton();
        labelKullaniciAdi = new javax.swing.JLabel();
        LabelSifre = new javax.swing.JLabel();
        kayit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("giriş Ekranı");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(456, 190));
        setMaximumSize(new java.awt.Dimension(21474, 21474));
        setMinimumSize(new java.awt.Dimension(30, 30));
        setName("girisEkrani"); // NOI18N

        sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreActionPerformed(evt);
            }
        });

        kullaniciAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciAdiActionPerformed(evt);
            }
        });

        butonGiris.setBackground(new java.awt.Color(0, 255, 255));
        butonGiris.setForeground(new java.awt.Color(0, 0, 0));
        butonGiris.setText("Giriş");
        butonGiris.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butonGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonGirisActionPerformed(evt);
            }
        });

        labelKullaniciAdi.setText("Kullanıcı Adı:");

        LabelSifre.setText("Şifre:");

        kayit.setBackground(new java.awt.Color(51, 255, 0));
        kayit.setForeground(new java.awt.Color(0, 0, 0));
        kayit.setText("Kayıt ol");
        kayit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout girisEkraniLayout = new javax.swing.GroupLayout(girisEkrani);
        girisEkrani.setLayout(girisEkraniLayout);
        girisEkraniLayout.setHorizontalGroup(
            girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girisEkraniLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelKullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelSifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kayit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sifre, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(butonGiris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        girisEkraniLayout.setVerticalGroup(
            girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girisEkraniLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelKullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sifre))
                .addGap(18, 18, 18)
                .addGroup(girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonGiris)
                    .addComponent(kayit))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(girisEkrani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(girisEkrani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>                        

  
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        girisEkrani = new javax.swing.JPanel();
        sifre = new javax.swing.JPasswordField();
        kullaniciAdi = new java.awt.TextField();
        butonGiris = new javax.swing.JButton();
        labelKullaniciAdi = new javax.swing.JLabel();
        LabelSifre = new javax.swing.JLabel();
        kayit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("giriş Ekranı");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(456, 190));
        setMaximumSize(new java.awt.Dimension(21474, 21474));
        setMinimumSize(new java.awt.Dimension(30, 30));
        setName("girisEkrani"); // NOI18N

        girisEkrani.setBackground(new java.awt.Color(255, 204, 204));

        sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreActionPerformed(evt);
            }
        });

        kullaniciAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciAdiActionPerformed(evt);
            }
        });

        butonGiris.setBackground(new java.awt.Color(0, 255, 255));
        butonGiris.setForeground(new java.awt.Color(0, 0, 0));
        butonGiris.setText("Giriş");
        butonGiris.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butonGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonGirisActionPerformed(evt);
            }
        });

        labelKullaniciAdi.setText("Kullanıcı Adı:");

        LabelSifre.setText("Şifre:");

        kayit.setBackground(new java.awt.Color(51, 255, 0));
        kayit.setForeground(new java.awt.Color(0, 0, 0));
        kayit.setText("Kayıt ol");
        kayit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout girisEkraniLayout = new javax.swing.GroupLayout(girisEkrani);
        girisEkrani.setLayout(girisEkraniLayout);
        girisEkraniLayout.setHorizontalGroup(
            girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girisEkraniLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelKullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelSifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kayit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sifre, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(butonGiris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        girisEkraniLayout.setVerticalGroup(
            girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girisEkraniLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelKullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sifre))
                .addGap(18, 18, 18)
                .addGroup(girisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonGiris)
                    .addComponent(kayit))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(girisEkrani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(girisEkrani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullaniciAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullaniciAdiActionPerformed

    private void sifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sifreActionPerformed

    private void butonGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonGirisActionPerformed
     char[] sifreAl = sifre.getPassword();
       String parolayiCevir = String.valueOf(sifreAl);
       String gelenKullanici = kullaniciAdi.getText();
       // System.out.println(parolayiCevir);
       // System.out.println(gelenKullanici);
         File fl = new File("kullanicilar","kullanicisifre.txt");
      try{
      Scanner sc = new Scanner(fl);
      

      
      while(sc.hasNextLine())
      {         // System.out.println(sc.nextLine());
          String kulsifre = sc.nextLine();
          String[] parcala = kulsifre.split(";");
          if(gelenKullanici.equals(parcala[1]) && parolayiCevir.equals(parcala[2]))//sisteme gir
          {// System.out.print("heyyo");
            if(parcala[0].equals("1") || parcala[0].equals("2") || parcala[0].equals("3") || parcala[0].equals("4"))//ilk 4 kullanıcı = admin
            {
             new YoneticiEkrani();
            }
            else{
            new  UygulamaEkrani();
                }
         dispose();
          }         
      } //  JOptionPane.showMessageDialog(rootPane,"Giriş başarısız" ,"Hata", HEIGHT);
      sc.close();
      }catch(FileNotFoundException e){
      e.printStackTrace();
      }   
    }//GEN-LAST:event_butonGirisActionPerformed

    private void kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitActionPerformed

       new KayitEkrani();
        dispose();
    }//GEN-LAST:event_kayitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   
          
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }
    
    
    public void DosyaYaz(String dt)
    {
         //String deneme = "";
        
        File fl = new File("kullanicilar","kullanicisifre.txt");
          try{ 
   FileOutputStream fos = new FileOutputStream(fl,true);
/*    DataInputStream dts = new DataInputStream(fos);
    BufferedReader bfr = new BufferedReader(new InputStreamReader(dts));
  */  
    /*
    deneme = bfr.readLine();
    dts.close();
                  System.out.println(deneme);

    */
    fos.write(dt.getBytes());
    fos.flush();
    fos.close();
    
    
    
    
      }catch(Exception e)
      {
          System.err.println("Hata: "+e.getMessage());
      }
    
    }
    
    
    public void DosyaOku()
    {
            File fl = new File("kullanicilar","kullanicisifre.txt");
      try{
      Scanner sc = new Scanner(fl);
      while(sc.hasNextLine())
      {
          System.out.println(sc.nextLine());
      }
      sc.close();
      }catch(FileNotFoundException e){
      e.printStackTrace();
      }
            
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelSifre;
    private javax.swing.JButton butonGiris;
    private javax.swing.JPanel girisEkrani;
    private javax.swing.JButton kayit;
    private java.awt.TextField kullaniciAdi;
    private javax.swing.JLabel labelKullaniciAdi;
    private javax.swing.JPasswordField sifre;
    // End of variables declaration//GEN-END:variables
    private String varsayilanKullaniciAdi = "admin";
    private String varsayilanSifre = "admin";





}
